### PR TITLE
Add shield badges to backport

### PR DESCRIPTION
**Pull request by sqren**
This PR adds shields.io badges which makes it possible to see the status of the backport pull request. This will indicate whether the PR is open, closed or merged.

image

### CODE REVIEW

**Comment by brianseeders** [comment]
buildkite build this

**Comment by brianseeders** [comment]
buildkite build this

**Comment by brianseeders** [comment]
https://buildkite.com/elastic/kibana-github-actions-pr/builds/5

**Review by brianseeders — APPROVED** [review]
Thanks for adding this, pretty sweet

**Comment by sqren** [comment]
Let's keep an eye on how this actually renders

**Comment by sqren** [comment]
Btw. thanks for merging!

**Comment by sqren** [comment]
Oh, I see you already fixed the formatting issues 👍 
https://github.com/elastic/kibana-github-actions/commit/f09f95256bd7d94c9a466d60b0058ed6e8ebb568

**Pull request merged**
